import { createContext, useContext, useState, ReactNode } from 'react';
import { appExtraEn, appExtraEs } from './translations/appExtra';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    let result = typeof value === 'string' ? value : key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        result = result.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
      }
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  es: {
    currency: 'MXN',
    hero: {
      location: 'La Veleta, Tulum',
      brand: 'Hiperlocal',
      tagline: 'Hospitality-Integrated Farming Systems',
      title1: 'Verduras Sostenibles',
      title2: 'Distancia Cero',
      description: 'Herramientas de tecnología agrícola para diseñar, implementar y monitorear cualquier operación de cultivo.',
      stepDesign: 'Diseña',
      stepDesignLabel: 'Diseña un sistema',
      stepPlan: 'Planifica',
      stepPlanLabel: 'Modela costos y retorno',
      stepTrack: 'Monitorea',
      stepTrackLabel: 'Registra ciclos y cosechas',
      stepOperate: 'Opera',
      stepOperateLabel: 'Administra sistemas guardados',
      nextHint: 'Haz clic en Siguiente abajo para diseñar un sistema agTech',
      established: 'Est. 2025 — Tulum, Q.Roo',
    },
    configurator: {
      title: 'Configurador de Sistemas',
      subtitle: 'Diseña Tu',
      subtitle2: 'Sistema de Granja',
      description: 'Añade sistemas de plantas para configurar tu operación de cultivo.',
      systemType: 'Tipo de Sistema',
      nft: 'NFT (Técnica de Película Nutriente)',
      kratky: 'Kratky (Pasivo)',
      verticalWall: 'Sistema de Pared Vertical',
      microgreens: 'Bandejas de Microgreens',
      racks: 'Estantes',
      roomSize: 'Tamaño de Espacio (m²)',
      cropMix: 'Mezcla de Cultivos',
      herbsGreens: 'Hierbas y Verduras',
      microgreensFocus: 'Enfoque en Microgreens',
      edibleFlowers: 'Flores Comestibles',
      mixedPremium: 'Mezcla Premium',
      projectedPerformance: 'Rendimiento Proyectado',
      financialModel: 'Modelo Financiero',
      startupCost: 'Costo Inicial',
      oneTime: 'Una vez',
      monthlyOperating: 'Costo Operativo',
      monthly: 'Mensual',
      estRevenue: 'Ingresos Est.',
      grossMargin: 'Margen Bruto',
      margin: 'Margen',
      resourceUsage: 'Uso de Recursos',
      electricity: 'Electricidad',
      water: 'Agua',
      expectedYield: 'Rendimiento Esperado',
      paybackPeriod: 'Período de Recuperación',
      months: 'meses',
    },
    crops: {
      title: 'Rentabilidad de',
      subtitle: 'Cultivos',
      subtitle2: 'Base de Datos',
      all: 'Todos',
      herb: 'Hierba',
      green: 'Verdura',
      microgreen: 'Microgreen',
      flower: 'Flor',
      revenue: 'Ingresos',
      cycle: 'Ciclo',
      ease: 'Facilidad',
      easy: 'Fácil',
      medium: 'Medio',
      advanced: 'Avanzado',
      highDemand: 'Alta demanda',
      mediumDemand: 'Demanda media',
      lowDemand: 'Baja demanda',
      humiditySensitive: 'Sensible a humedad',
      fresh: 'Frescura+',
      basil: 'Albahaca Dulce',
      basilNotes: 'Alta demanda en hospitalidad premium, rotación rápida',
      mint: 'Menta',
      mintNotes: 'Favorita de bares y coctelería, muy resistente',
      cilantro: 'Cilantro',
      cilantroNotes: 'Esencial en cocina mexicana, alto volumen',
      arugula: 'Arúgula',
      arugulaNotes: 'Crecimiento rápido, excelentes márgenes',
      lettuce: 'Lechuga Mantequilla',
      lettuceNotes: 'Base confiable, demanda consistente',
      edibleFlowersMix: 'Mezcla de Flores Comestibles',
      flowersNotes: 'Ultra-premium, solo restaurantes de alta gama',
      microgreensBlend: 'Mezcla de Microgreens',
      microgreensNotes: 'Ciclo más rápido, mayor densidad de ingresos',
      shiso: 'Shiso (Perilla)',
      shisoNotes: 'Nicho restaurantes japoneses/fusión',
      peaShoots: 'Brotes de Guisante',
      peaShootsNotes: 'Excelente para ensaladas, atractivo como guarnición',
    },
    partnerships: {
      title: 'Integración de',
      subtitle: 'Asociación',
      description: 'Explora estructuras de asociación diseñadas para el ecosistema de mixology artistica y comida craft de Tulum.',
      freeSpace: 'Asociación Espacio-Compartido',
      freeSpaceDesc: 'Utiliza espacio no usado de cocina o almacén con infraestructura mínima',
      rentedRoom: 'Sala de Microgranja Rentada',
      rentedRoomDesc: 'Sala dedicada con clima controlado y automatización completa',
      hotelInstallation: 'Instalación Hotel Boutique',
      hotelInstallationDesc: 'Granja integrada personalizada sirviendo restaurant y amenidades del hotel',
      barWall: 'Pared de Hierbas Visible en Bar',
      barWallDesc: 'Instalación de pared viva arquitectónica detrás del área de bar',
      containerFarm: 'Granja en Contenedor',
      containerFarmDesc: 'Unidad de granja modular completamente autónoma',
      startup: 'Inicio',
      revenue: 'Ingresos/mes',
      risk: 'Riesgo',
      aesthetic: 'Estética',
      experience: 'Experiencia',
      advantages: 'Ventajas',
      considerations: 'Consideraciones',
      idealFor: 'Ideal Para',
      setup: 'Instalación',
      low: 'Bajo',
      medium: 'Medio',
      high: 'Alto',
      complexity: 'Complejidad',
      freeSpaceAdvantages: [
        'Inversión inicial mínima',
        'Bajo compromiso del lugar',
        'Implementación rápida',
        'Fácil de probar la asociación',
      ],
      freeSpaceConsiderations: [
        'Visibilidad limitada para los huéspedes',
        'Dependiente de disponibilidad de espacio',
        'Puede competir por espacio durante crecimiento',
      ],
      freeSpaceIdealFor: 'Asociaciones iniciales, lugares enfocados en cocina',
      rentedRoomAdvantages: [
        'Ambiente controlado',
        'Mayores rendimientos y consistencia',
        'Operación profesional',
        'Espacio para expansión',
      ],
      rentedRoomConsiderations: [
        'Inversión inicial mayor',
        'Compromiso de renta requerido',
        'Costos de control de clima',
        'Instalación más compleja',
      ],
      rentedRoomIdealFor: 'Lugares establecidos, múltiples restaurantes',
      hotelAdvantages: [
        'Alineación de marca premium',
        'Múltiples fuentes de ingresos',
        'Alta visibilidad para huéspedes',
        'Valor de marketing de sostenibilidad',
      ],
      hotelConsiderations: [
        'Inversión significativa',
        'Tiempo de instalación más largo',
        'Requiere asociación sólida',
        'Mayor complejidad operativa',
      ],
      hotelIdealFor: 'Hoteles eco-lujo, resorts de bienestar',
      barWallAdvantages: [
        'Impacto visual impresionante',
        'Guarnición de cócteles en vivo',
        'Atractivo para redes sociales',
        'Posicionamiento de marca premium',
      ],
      barWallConsiderations: [
        'Alta visibilidad = altos estándares',
        'Limitado a hierbas y guarniciones',
        'Mantenimiento estético crítico',
        'Menos escalable',
      ],
      barWallIdealFor: 'Bares de cócteles, restaurantes de alta gama',
      containerAdvantages: [
        'Máxima capacidad de producción',
        'Operación completamente independiente',
        'Activo reubicable',
        'Independiente del clima',
      ],
      containerConsiderations: [
        'Costo inicial más alto',
        'Requiere espacio exterior',
        'Permisos complejos',
        'Costos operativos significativos',
      ],
      containerIdealFor: 'Resorts grandes, operaciones multi-lugar',
    },
    problem: {
      title: 'La Situacion de',
      subtitle: 'Hospitalidad en Tulum',
      description: 'La industria hotelera de Tulum enfrenta desafíos críticos de cadena de suministro que impactan tanto la calidad como la sostenibilidad.',
      currentReality: 'La Realidad Actual',
      solution: 'La Solución',
      solutionText: 'Las granjas hidropónicas in situ eliminan estos problemas por completo',
      supplyChain: {
        title: 'Fragilidad de Cadena de Suministro',
        description: 'Las hierbas llegan marchitas después de 8-12 horas de transporte desde Playa del Carmen o Cancún.',
        impact: '40-60% pérdida de calidad',
      },
      inconsistentAvailability: {
        title: 'Disponibilidad Inconsistente',
        description: 'Los ingredientes premium desaparecen a mitad del servicio cuando los proveedores se quedan sin existencias.',
        impact: 'Limitaciones del menú',
      },
      zeroStorytelling: {
        title: 'Cero Valor Narrativo',
        description: 'Los productos genéricos no ofrecen diferenciación experiencial para cócteles de $18.',
        impact: 'Posicionamiento premium perdido',
      },
      wasteSpoilage: {
        title: 'Desperdicio y Deterioro',
        description: 'La vida útil se mide en horas, no en días. El cilantro cuesta $280/kg pero la mitad va a la basura.',
        impact: '30-50% tasas de desperdicio',
      },
      limitedVariety: {
        title: 'Variedad Limitada',
        description: 'Los proveedores solo tienen lo básico. ¿Microgreens, flores comestibles, hierbas especiales? Pedido especial, quizás.',
        impact: 'Restricciones creativas',
      },
      noGuestExperience: {
        title: 'Sin Experiencia para Huéspedes',
        description: 'Los ingredientes son invisibles. De-la-granja-a-la-mesa es un reclamo de marketing, no una realidad visible.',
        impact: 'Percepción commoditizada',
      },
    },
    solution: {
      title: 'Nuestra',
      subtitle: 'Solución',
      description: 'Sistemas hidropónicos modulares in situ que transforman espacios no utilizados en granjas de producción premium—eliminando la cadena de suministro por completo.',
      valueTitle: 'Granja a Mesa en Metros, No Kilómetros',
      valueDescription: 'Instalamos y operamos sistemas hidropónicos de grado comercial directamente en tu lugar. Tus hierbas, microgreens y flores comestibles crecen a metros de tu cocina o bar—cosechadas bajo pedido, frescas al 100%, y sin desperdicio de transporte.',
      benefit1Title: 'Cosecha Instantánea',
      benefit1Desc: 'Del sistema a la mesa en minutos. Cero tiempo de transporte significa máxima frescura y vida útil.',
      benefit2Title: 'Calidad Garantizada',
      benefit2Desc: 'Control de ambiente completo asegura producción consistente año redondo, sin importar el clima.',
      benefit3Title: 'Costo Predecible',
      benefit3Desc: 'Sin fluctuaciones de precios de mercado. Costos fijos mensuales con producción garantizada.',
      benefit4Title: 'Diferenciación Premium',
      benefit4Desc: 'Instalaciones visibles que cuentan tu historia de sostenibilidad y elevan la experiencia del huésped.',
      keyFeatures: 'Características Clave',
      feature1: 'Instalación y configuración completa',
      feature2: 'Mantenimiento y monitoreo continuo',
      feature3: 'Reposición garantizada de suministros',
      feature4: 'Programas de capacitación del personal',
      feature5: 'Sistemas de cosecha bajo demanda',
      feature6: 'Integración de marca visible',
      cta: 'Listo para eliminar tu cadena de suministro y comenzar a cosechar en el lugar. Exploremos cómo funciona.',
    },
    dashboard: {
      title: 'Panel de',
      subtitle: 'Operaciones',
      systemTime: 'Hora del Sistema',
      temperature: 'Temperatura',
      humidity: 'Humedad',
      nutrientEC: 'EC de Nutrientes',
      phLevel: 'Nivel de pH',
      reservoirLevel: 'Nivel de Reservorio',
      airflow: 'Flujo de Aire',
      powerDraw: 'Consumo Eléctrico',
      lightingSchedule: 'Programación de Luz',
      systemStatus: 'Estado del Sistema',
      optimal: 'Óptimo',
      warning: 'Advertencia',
      range: 'Rango',
      min24h: 'Mín (24h)',
      max24h: 'Máx (24h)',
      lastAdjusted: 'Último ajuste',
      nextCheck: 'Próxima revisión',
      ago: 'hace',
      capacity: 'capacidad',
      waterUsage24h: 'Uso de agua (24h)',
      refillScheduled: 'Recarga programada',
      tomorrow: 'Mañana',
      estRemaining: 'Est. restante',
      days: 'días',
      active: 'Activo',
      fanSpeed: 'Velocidad ventilador',
      airExchanges: 'Intercambios aire/h',
      dailyConsumption: 'Consumo diario',
      monthlyEst: 'Est. mensual',
      activeCycle: 'Ciclo Activo',
      on: 'ENCENDIDO',
      currentIntensity: 'Intensidad actual',
      nextOff: 'Próximo APAGADO',
      spectrum: 'Espectro',
      full: 'Completo',
      ppfdAvg: 'PPFD prom',
      allSystemsNominal: 'Todos los Sistemas Nominales',
      lastSystemCheck: 'Última revisión del sistema',
      minutesAgo: 'minutos atrás',
      nutrientTopUp: 'Recarga de nutrientes programada',
      scheduled: 'Programado',
      ok: 'OK',
    },
    summary: {
      title: 'Modelo',
      subtitle: 'Financiero Completo',
      monthlyBreakdown: 'Desglose Mensual',
      revenue: 'Ingresos',
      costs: 'Costos',
      netProfit: 'Utilidad Neta',
      margin: 'Margen',
      annualProjection: 'Proyección Anual',
      year1: 'Año 1',
      year3: 'Año 3',
      year5: 'Año 5',
      roi: 'ROI',
      keyMetrics: 'Métricas Clave',
      paybackPeriod: 'Período de Recuperación',
      months: 'meses',
      grossMargin: 'Margen Bruto',
      operatingMargin: 'Margen Operativo',
      assumptions: 'Supuestos',
      systemSize: 'Tamaño del Sistema',
      avgYield: 'Rendimiento Promedio',
      avgPrice: 'Precio Promedio',
      utilizationRate: 'Tasa de Utilización',
    },
    financial: {
      title: 'Planificación Financiera',
      subtitle: 'Costos',
      subtitle2: 'Operativos',
      description: 'Ajusta tus costos operativos mensuales basados en tu ubicación y configuración.',
      basedOnConfig: 'Basado en Tu Configuración',
      system: 'Sistema',
      racks: 'Estantes',
      space: 'Espacio',
      consumption: 'Consumo',
      operatingCosts: 'Costos Operativos',
      monthlyCosts: 'Costos Mensuales',
      electricityKwh: 'Electricidad (MXN/kWh)',
      rentMonth: 'Renta (MXN/mes)',
      laborMonth: 'Mano de Obra (MXN/mes)',
      nutrientsSupplies: 'Nutrientes y Suministros (MXN/mes)',
      totalMonthlyCosts: 'Total Costos Mensuales',
      revenueModel: 'Modelo de Ingresos',
      activeClients: 'Clientes Activos',
      avgPriceKg: 'Precio Prom (MXN/kg)',
      harvestsPerMonth: 'Cosechas por Mes',
      harvests: 'cosechas',
      totalMonthlyRevenue: 'Total Ingresos Mensuales',
      resultsProjections: 'Resultados y Proyecciones',
      monthlyPL: 'P&G Mensual',
      margin: 'margen',
      revenue: 'Ingresos',
      operatingCostsShort: 'Costos Operativos',
      grossProfit: 'Utilidad Bruta',
      annualProjection: 'Proyección Anual',
      costs: 'Costos',
      profit: 'Utilidad',
      breakEvenAnalysis: 'Análisis de Punto de Equilibrio',
      estStartupInvestment: 'Inversión Inicial Est.',
      monthlyProfit: 'Utilidad Mensual',
      paybackPeriod: 'Período de Recuperación',
      mo: 'meses',
      costBreakdown: 'Desglose de Costos',
      electricity: 'Electricidad',
      rent: 'Renta',
      labor: 'Mano de Obra',
      nutrients: 'Nutrientes',
      ingresos: 'Ingresos',
      proyectados: 'Proyectados',
      rendimientoBase: 'Rendimiento Base',
      usoAgua: 'Uso de Agua',
      configuracionIngresos: 'Configuración de Ingresos',
      precioPromedio: 'Precio Promedio',
      cosechasPorMes: 'Cosechas por Mes',
      totalIngresosMensual: 'Total Ingresos Mensual',
      desgloseInversion: 'Desglose de Inversión Inicial',
      sistemaBase: 'Sistema Base',
      automatizacion: 'Automatización',
      ambiente: 'Ambiente',
      clima: 'Clima',
      aireLibre: 'Aire Libre',
      total: 'Total',
      inicial: 'Inicial',
      mensual: 'Mensual',
      inversion: 'Inversión',
      costos: 'Costos',
      bruto: 'Bruto',
      pl: 'P&G',
      usoRecursos: 'Uso de Recursos',
      periodoRecuperacion: 'Período de Recuperación',
      meses: 'meses',
      proyeccionAnual: 'Proyección Anual',
      año: 'Año',
      desgloseCostos: 'Desglose de Costos',
      metricasProduccion: 'Métricas de Producción',
      produccionTotal: 'Producción Total',
      consumoElectrico: 'Consumo Eléctrico',
      ingresoPorKg: 'Ingreso por Kg',
      frecuenciaCosecha: 'Frecuencia de Cosecha',
    },
    vision: {
      title: 'Oportunidades Futuras',
      subtitle: 'Escalando',
      subtitle2: 'Más Allá de Hoy',
      description: 'De instalaciones boutique a infraestructura regional—construyendo el futuro de la agricultura hiperlocal de hospitalidad en la Riviera Maya.',
      installationsBy2027: 'Instalaciones para 2027',
      hospitalityPartners: 'Socios de Hospitalidad',
      monthlyProduction: 'Producción Mensual',
      wasteReduction: 'Reducción de Residuos',
      product: 'Producto',
      service: 'Servicio',
      infrastructure: 'Infraestructura',
      education: 'Educación',
      transformative: 'Transformador',
      high: 'Alto',
      medium: 'Medio',
      impact: 'impacto',
      hotelIntegration: 'Integración Hotel de Lujo',
      hotelIntegrationDesc: 'Sistemas granja-a-mesa integrados en hoteles boutique, creando experiencias inmersivas de sostenibilidad para huéspedes.',
      experientialGrowing: 'Instalaciones de Cultivo Experiencial',
      experientialGrowingDesc: 'Paredes vivas arquitectónicas y sistemas de cultivo visibles diseñados como instalaciones centrales para lugares de alta gama.',
      wellnessResort: 'Asociaciones Resort de Bienestar',
      wellnessResortDesc: 'Sistemas de agricultura integrados apoyando programas de bienestar, talleres nutricionales y cocina curativa.',
      workshops: 'Serie de Talleres Educativos',
      workshopsDesc: 'Talleres de agricultura hidropónica para personal de hospitalidad, residentes y viajeros enfocados en sostenibilidad.',
      brandedProduce: 'Línea de Productos Locales de Marca',
      brandedProduceDesc: 'Línea de productos premium "Cultivado en Tulum" distribuida a lugares de hospitalidad regionales y mercados especializados.',
      climateAdaptive: 'Infraestructura Adaptativa al Clima',
      climateAdaptiveDesc: 'Sistemas de agricultura resilientes diseñados para desafíos climáticos tropicales, preparación para huracanes y escasez de agua.',
      buildingFuture: 'Construyendo el Futuro Alimentario Sostenible de Tulum',
      buildingFutureDesc: 'Imaginamos una Riviera Maya donde cada lugar de hospitalidad tenga acceso a sistemas de producción hiperlocal y sin residuos—creando un ecosistema alimentario resiliente y sostenible que mejora las experiencias de los huéspedes mientras protege la belleza natural de la región.',
    },
    nav: {
      hero: 'El Concepto',
      problem: 'El Problema',
      solution: 'Solución',
      configurator: 'Diseño de Sistema',
      crops: 'Cultivos',
      partnerships: 'Asociaciones',
      dashboard: 'Panel',
      financial: 'Costos',
      summary: 'Resumen Financiero',
      vision: 'Visión',
      scroll: 'Desplaza o presiona ↓',
      swipe: 'Desliza hacia arriba',
      nextSlide: 'Sig.',
      prevSlide: 'Ant.',
      planning: 'Ideación',
      operations: 'Operaciones',
      learn: 'Aprender',
      about: 'Acerca de',
      language: 'Idioma',
    },
    ...appExtraEs,
  },
  en: {
    currency: 'MXN',
    hero: {
      location: 'La Veleta, Tulum',
      brand: 'Hyperlocal',
      tagline: 'Hospitality-Integrated Farming Systems',
      title1: 'Sustainable Greens',
      title2: 'Zero Distance',
      description: 'Ag-tech tools to design, implement and trackplant cultivation operations at any scale.',
      stepDesign: 'Design',
      stepDesignLabel: 'Design a system',
      stepPlan: 'Plan',
      stepPlanLabel: 'Financially model the farm',
      stepTrack: 'Track',
      stepTrackLabel: 'Log grow cycles & harvests',
      stepOperate: 'Operate',
      stepOperateLabel: 'Manage saved systems',
      nextHint: 'Click next below to design an agTech system',
      established: 'Est. 2025 — Tulum, Q.Roo',
    },
    configurator: {
      title: 'System Configurator',
      subtitle: 'Design Your',
      subtitle2: 'Farm System',
      description: 'Add plant systems to configure your plant cultivation operation.',
      systemType: 'System Type',
      nft: 'NFT (Nutrient Film Technique)',
      kratky: 'Kratky (Passive)',
      verticalWall: 'Vertical Wall System',
      microgreens: 'Microgreens Trays',
      racks: 'Racks',
      roomSize: 'Room Size (m²)',
      cropMix: 'Crop Mix',
      herbsGreens: 'Herbs & Greens',
      microgreensFocus: 'Microgreens Focus',
      edibleFlowers: 'Edible Flowers',
      mixedPremium: 'Mixed Premium',
      projectedPerformance: 'Projected Performance',
      financialModel: 'Financial Model',
      startupCost: 'Startup Cost',
      oneTime: 'One-time',
      monthlyOperating: 'Operating Cost',
      monthly: 'Monthly',
      estRevenue: 'Est. Revenue',
      grossMargin: 'Gross Margin',
      margin: 'Margin',
      resourceUsage: 'Resource Usage',
      electricity: 'Electricity',
      water: 'Water',
      expectedYield: 'Expected Yield',
      paybackPeriod: 'Payback Period',
      months: 'months',
    },
    crops: {
      title: 'Profitability',
      subtitle: 'Database',
      subtitle2: '',
      all: 'All',
      herb: 'Herb',
      green: 'Green',
      microgreen: 'Microgreen',
      flower: 'Flower',
      revenue: 'Revenue',
      cycle: 'Cycle',
      ease: 'Ease',
      easy: 'Easy',
      medium: 'Medium',
      advanced: 'Advanced',
      highDemand: 'High demand',
      mediumDemand: 'Medium demand',
      lowDemand: 'Low demand',
      humiditySensitive: 'Humidity sensitive',
      fresh: 'Fresh+',
      basil: 'Sweet Basil',
      basilNotes: 'Premium hospitality demand, fast turnover',
      mint: 'Mint',
      mintNotes: 'Bar & cocktail favorite, very hardy',
      cilantro: 'Cilantro',
      cilantroNotes: 'Mexican cuisine essential, high volume',
      arugula: 'Arugula',
      arugulaNotes: 'Fast-growing, excellent margins',
      lettuce: 'Butterhead Lettuce',
      lettuceNotes: 'Reliable staple, consistent demand',
      edibleFlowersMix: 'Edible Flowers Mix',
      flowersNotes: 'Ultra-premium, high-end restaurants only',
      microgreensBlend: 'Microgreens Blend',
      microgreensNotes: 'Fastest cycle, highest revenue density',
      shiso: 'Shiso (Perilla)',
      shisoNotes: 'Niche Japanese/fusion restaurants',
      peaShoots: 'Pea Shoots',
      peaShootsNotes: 'Great for salads, garnish appeal',
    },
    partnerships: {
      title: 'Partnership',
      subtitle: 'Integrations',
      description: 'Explore partnership structures designed for Tulum\'s craft and mixology ecosystem.',
      freeSpace: 'Free-Space Partnership',
      freeSpaceDesc: 'Utilize unused kitchen or storage space with minimal infrastructure',
      rentedRoom: 'Rented Microfarm Room',
      rentedRoomDesc: 'Dedicated climate-controlled room with full automation',
      hotelInstallation: 'Boutique Hotel Installation',
      hotelInstallationDesc: 'Custom integrated farm serving hotel restaurant and amenities',
      barWall: 'Visible Bar Herb Wall',
      barWallDesc: 'Architectural living wall installation behind bar area',
      containerFarm: 'Shipping Container Farm',
      containerFarmDesc: 'Fully self-contained modular farm unit',
      startup: 'Startup',
      revenue: 'Revenue/mo',
      risk: 'Risk',
      aesthetic: 'Aesthetic',
      experience: 'Experience',
      advantages: 'Advantages',
      considerations: 'Considerations',
      idealFor: 'Ideal For',
      setup: 'Setup',
      low: 'Low',
      medium: 'Medium',
      high: 'High',
      complexity: 'Complexity',
      freeSpaceAdvantages: [
        'Minimal upfront investment',
        'Low commitment from venue',
        'Quick implementation',
        'Easy to test partnership',
      ],
      freeSpaceConsiderations: [
        'Limited visibility to guests',
        'Dependent on space availability',
        'May compete for space during growth',
      ],
      freeSpaceIdealFor: 'Initial partnerships, kitchen-focused venues',
      rentedRoomAdvantages: [
        'Controlled environment',
        'Higher yields and consistency',
        'Professional operation',
        'Room for expansion',
      ],
      rentedRoomConsiderations: [
        'Higher initial investment',
        'Rent commitment required',
        'Climate control costs',
        'More complex setup',
      ],
      rentedRoomIdealFor: 'Established venues, multiple restaurants',
      hotelAdvantages: [
        'Premium brand alignment',
        'Multiple revenue streams',
        'High guest visibility',
        'Sustainability marketing value',
      ],
      hotelConsiderations: [
        'Significant investment',
        'Longer setup time',
        'Requires strong partnership',
        'Higher operational complexity',
      ],
      hotelIdealFor: 'Eco-luxury hotels, wellness resorts',
      barWallAdvantages: [
        'Stunning visual impact',
        'Live cocktail garnish',
        'Social media appeal',
        'Premium brand positioning',
      ],
      barWallConsiderations: [
        'High visibility = high standards',
        'Limited to herbs and garnishes',
        'Aesthetic maintenance critical',
        'Less scalable',
      ],
      barWallIdealFor: 'Cocktail bars, high-end restaurants',
      containerAdvantages: [
        'Maximum production capacity',
        'Fully independent operation',
        'Relocatable asset',
        'Climate-independent',
      ],
      containerConsiderations: [
        'Highest upfront cost',
        'Requires outdoor space',
        'Complex permitting',
        'Significant operating costs',
      ],
      containerIdealFor: 'Large resorts, multi-venue operations',
    },
    problem: {
      title: 'The Tulum',
      subtitle: 'Hospitality Space',
      description: 'Tulum\'s hospitality industry faces critical supply chain challenges that impact both quality and sustainability.',
      currentReality: 'The Current Reality',
      solution: 'The Solution',
      solutionText: 'On-site hydroponic farms eliminate these problems entirely',
      supplyChain: {
        title: 'Supply Chain Fragility',
        description: 'Herbs arrive wilted after 8-12 hour transport from Playa del Carmen or Cancún.',
        impact: '40-60% quality loss',
      },
      inconsistentAvailability: {
        title: 'Inconsistent Availability',
        description: 'Premium ingredients disappear mid-service when suppliers run out.',
        impact: 'Menu limitations',
      },
      zeroStorytelling: {
        title: 'Zero Storytelling Value',
        description: 'Generic produce offers no experiential differentiation for $18 cocktails.',
        impact: 'Missed premium positioning',
      },
      wasteSpoilage: {
        title: 'Waste & Spoilage',
        description: 'Shelf life measured in hours, not days. Cilantro costs $280/kg but half goes in the trash.',
        impact: '30-50% waste rates',
      },
      limitedVariety: {
        title: 'Limited Variety',
        description: 'Suppliers stock basics only. Microgreens, edible flowers, specialty herbs? Special order, maybe.',
        impact: 'Creative constraints',
      },
      noGuestExperience: {
        title: 'No Guest Experience',
        description: 'Ingredients are invisible. Farm-to-table is a marketing claim, not a visible reality.',
        impact: 'Commoditized perception',
      },
    },
    solution: {
      title: 'Our',
      subtitle: 'Solution',
      description: 'On-site modular hydroponic systems that transform unused spaces into premium production farms—eliminating the supply chain entirely.',
      valueTitle: 'Farm-to-Table in Meters, Not Kilometers',
      valueDescription: 'We install and operate commercial-grade hydroponic systems directly at your venue. Your herbs, microgreens, and edible flowers grow meters from your kitchen or bar—harvested on demand, 100% fresh, and zero transport waste.',
      benefit1Title: 'Instant Harvest',
      benefit1Desc: 'From system to plate in minutes. Zero transport time means maximum freshness and shelf life.',
      benefit2Title: 'Guaranteed Quality',
      benefit2Desc: 'Full environmental control ensures consistent year-round production, regardless of weather.',
      benefit3Title: 'Predictable Cost',
      benefit3Desc: 'No market price fluctuations. Fixed monthly costs with guaranteed output.',
      benefit4Title: 'Premium Differentiation',
      benefit4Desc: 'Visible installations that tell your sustainability story and elevate the guest experience.',
      keyFeatures: 'Key Features',
      feature1: 'Full installation and setup',
      feature2: 'Ongoing maintenance and monitoring',
      feature3: 'Guaranteed supply replenishment',
      feature4: 'Staff training programs',
      feature5: 'On-demand harvest systems',
      feature6: 'Visible brand integration',
      cta: 'Ready to eliminate your supply chain and start harvesting on-site. Let\'s explore how it works.',
    },
    dashboard: {
      title: 'Operations',
      subtitle: 'Dashboard',
      systemTime: 'System Time',
      temperature: 'Temperature',
      humidity: 'Humidity',
      nutrientEC: 'Nutrient EC',
      phLevel: 'pH Level',
      reservoirLevel: 'Reservoir Level',
      airflow: 'Airflow',
      powerDraw: 'Power Draw',
      lightingSchedule: 'Lighting Schedule',
      systemStatus: 'System Status',
      optimal: 'Optimal',
      warning: 'Warning',
      range: 'Range',
      min24h: 'Min (24h)',
      max24h: 'Max (24h)',
      lastAdjusted: 'Last adjusted',
      nextCheck: 'Next check',
      ago: 'ago',
      capacity: 'capacity',
      waterUsage24h: 'Water usage (24h)',
      refillScheduled: 'Refill scheduled',
      tomorrow: 'Tomorrow',
      estRemaining: 'Est. remaining',
      days: 'days',
      active: 'Active',
      fanSpeed: 'Fan speed',
      airExchanges: 'Air exchanges/h',
      dailyConsumption: 'Daily consumption',
      monthlyEst: 'Monthly est.',
      activeCycle: 'Active Cycle',
      on: 'ON',
      currentIntensity: 'Current intensity',
      nextOff: 'Next OFF',
      spectrum: 'Spectrum',
      full: 'Full',
      ppfdAvg: 'PPFD avg',
      allSystemsNominal: 'All Systems Nominal',
      lastSystemCheck: 'Last system check',
      minutesAgo: 'minutes ago',
      nutrientTopUp: 'Nutrient top-up scheduled',
      scheduled: 'Scheduled',
      ok: 'OK',
    },
    summary: {
      title: 'Complete',
      subtitle: 'Financial Model',
      monthlyBreakdown: 'Monthly Breakdown',
      revenue: 'Revenue',
      costs: 'Costs',
      netProfit: 'Net Profit',
      margin: 'Margin',
      annualProjection: 'Annual Projection',
      year1: 'Year 1',
      year3: 'Year 3',
      year5: 'Year 5',
      roi: 'ROI',
      keyMetrics: 'Key Metrics',
      paybackPeriod: 'Payback Period',
      months: 'months',
      grossMargin: 'Gross Margin',
      operatingMargin: 'Operating Margin',
      assumptions: 'Assumptions',
      systemSize: 'System Size',
      avgYield: 'Average Yield',
      avgPrice: 'Average Price',
      utilizationRate: 'Utilization Rate',
    },
    financial: {
      title: 'Financial Planning',
      subtitle: 'Operating',
      subtitle2: 'Costs',
      description: 'Adjust your monthly operating costs based on your location and configuration.',
      basedOnConfig: 'Based on Your Configuration',
      system: 'System',
      racks: 'Racks',
      space: 'Space',
      consumption: 'Consumption',
      operatingCosts: 'Operating Costs',
      monthlyCosts: 'Monthly Costs',
      electricityKwh: 'Electricity (MXN/kWh)',
      rentMonth: 'Rent (MXN/month)',
      laborMonth: 'Labor (MXN/month)',
      nutrientsSupplies: 'Nutrients & Supplies (MXN/month)',
      totalMonthlyCosts: 'Total Monthly Costs',
      revenueModel: 'Revenue Model',
      activeClients: 'Active Clients',
      avgPriceKg: 'Avg Price (MXN/kg)',
      harvestsPerMonth: 'Harvests per Month',
      harvests: 'harvests',
      totalMonthlyRevenue: 'Total Monthly Revenue',
      resultsProjections: 'Results & Projections',
      monthlyPL: 'Monthly P&L',
      margin: 'margin',
      revenue: 'Revenue',
      operatingCostsShort: 'Operating Costs',
      grossProfit: 'Gross Profit',
      annualProjection: 'Annual Projection',
      costs: 'Costs',
      profit: 'Profit',
      breakEvenAnalysis: 'Break-Even Analysis',
      estStartupInvestment: 'Est. Startup Investment',
      monthlyProfit: 'Monthly Profit',
      paybackPeriod: 'Payback Period',
      mo: 'mo',
      costBreakdown: 'Cost Breakdown',
      electricity: 'Electricity',
      rent: 'Rent',
      labor: 'Labor',
      nutrients: 'Nutrients',
      ingresos: 'Revenue',
      proyectados: 'Projected',
      rendimientoBase: 'Base Yield',
      usoAgua: 'Water Usage',
      configuracionIngresos: 'Revenue Configuration',
      precioPromedio: 'Average Price',
      cosechasPorMes: 'Harvests per Month',
      totalIngresosMensual: 'Total Monthly Revenue',
      desgloseInversion: 'Startup Investment Breakdown',
      sistemaBase: 'Base System',
      automatizacion: 'Automation',
      ambiente: 'Environment',
      clima: 'Climate',
      aireLibre: 'Open Air',
      total: 'Total',
      inicial: 'Startup',
      mensual: 'Monthly',
      inversion: 'Investment',
      costos: 'Costs',
      bruto: 'Gross',
      pl: 'P&L',
      usoRecursos: 'Resource Usage',
      periodoRecuperacion: 'Payback Period',
      meses: 'months',
      proyeccionAnual: 'Annual Projection',
      año: 'Year',
      desgloseCostos: 'Cost Breakdown',
      metricasProduccion: 'Production Metrics',
      produccionTotal: 'Total Production',
      consumoElectrico: 'Power Consumption',
      ingresoPorKg: 'Revenue per Kg',
      frecuenciaCosecha: 'Harvest Frequency',
    },
    vision: {
      title: 'Future Opportunities',
      subtitle: 'Scaling',
      subtitle2: 'Beyond Today',
      description: 'From boutique installations to regional infrastructure—building the future of hyperlocal hospitality farming across the Riviera Maya.',
      installationsBy2027: 'Installations by 2027',
      hospitalityPartners: 'Hospitality Partners',
      monthlyProduction: 'Monthly Production',
      wasteReduction: 'Waste Reduction',
      product: 'Product',
      service: 'Service',
      infrastructure: 'Infrastructure',
      education: 'Education',
      transformative: 'Transformative',
      high: 'High',
      medium: 'Medium',
      impact: 'impact',
      hotelIntegration: 'Luxury Hotel Integration',
      hotelIntegrationDesc: 'Embedded farm-to-table systems in boutique hotels, creating immersive sustainability experiences for guests.',
      experientialGrowing: 'Experiential Growing Installations',
      experientialGrowingDesc: 'Architectural living walls and visible growing systems designed as centerpiece installations for high-end venues.',
      wellnessResort: 'Wellness Resort Partnerships',
      wellnessResortDesc: 'Integrated farming systems supporting wellness programs, nutritional workshops, and healing cuisine.',
      workshops: 'Educational Workshop Series',
      workshopsDesc: 'Hydroponic farming workshops for hospitality staff, residents, and sustainability-focused travelers.',
      brandedProduce: 'Branded Local Produce Line',
      brandedProduceDesc: 'Premium "Tulum Grown" product line distributed to regional hospitality venues and specialty markets.',
      climateAdaptive: 'Climate-Adaptive Infrastructure',
      climateAdaptiveDesc: 'Resilient farming systems designed for tropical climate challenges, hurricane preparedness, and water scarcity.',
      buildingFuture: 'Building Tulum\'s Sustainable Food Future',
      buildingFutureDesc: 'We envision a Riviera Maya where every hospitality venue has access to hyperlocal, zero-waste produce systems—creating a resilient, sustainable food ecosystem that enhances guest experiences while protecting the region\'s natural beauty.',
    },
    nav: {
      hero: 'The Concept',
      problem: 'The Problem',
      solution: 'Solution',
      configurator: 'System Design',
      crops: 'Crops',
      partnerships: 'Partnerships',
      dashboard: 'Dashboard',
      financial: 'Costs',
      summary: 'Financial Summary',
      vision: 'Vision',
      scroll: 'Scroll or press ↓',
      swipe: 'Swipe up',
      nextSlide: 'Next',
      prevSlide: 'Back',
      planning: 'Ideation',
      operations: 'Operations',
      learn: 'Learn',
      about: 'About',
      language: 'Language',
    },
    ...appExtraEn,
  },
};
